### ISSUE TITLE
Allow editing of schedule data, not just deleting

### ISSUE THREAD

**Issue by Arthaey** [baitisj/anki-reset-card-scheduling#1]

**Comment by baitisj** [comment]
Hi Arthaey: could you provide a usage case -- an example that demonstrates how this feature would be useful / what it would do?

**Comment by Arthaey** [comment]
I had wanted it for easing import from another flashcard app. But instead I just went ahead and wrote a full-fledged importer for it, including preserving the statistics! :) Feel free to close this issue.
