### ISSUE TITLE
build.py

### ISSUE THREAD

**Issue by ankitest** [baitisj/anki-reset-card-scheduling#2]
For what is it intended?

**Comment by butcher211** [comment]
Hello @ankitest,
if you have installed Python (https://www.python.org/downloads/) than you can build the plugin by yourself. You just have to type "python3 build.py" and the buildscript creates a zip file which you can integrate into your anki pc client.

But it's still recommended to use the install code on anki plugins page: https://ankiweb.net/shared/info/1432861881

Greets,
Semih
